from __future__ import annotations

from typing import Protocol


class StorageBackend(Protocol):
    def exists(self, key: str) -> bool: ...

    def get_bytes(self, key: str) -> bytes: ...

    def put_bytes(self, key: str, data: bytes, content_type: str) -> None: ...

    def delete(self, key: str) -> None: ...
