export const profileCopy = {
  pageTitle: "个人中心",
  save: "保存",
  saving: "保存中...",
  saveFailed: "保存失败",
  nameSaved: "昵称已保存",
  avatarHint: "更换头像",
  avatarUpdated: "头像已更新",
  avatarUploadFailed: "上传头像失败",
  emailChange: "修改",
  cancel: "取消",
  newEmail: "新邮箱",
  verificationCode: "验证码",
  codePlaceholder: "6 位数字",
  sendCode: "获取验证码",
  confirmEmailChange: "确认更换",
  emailRequired: "请输入新邮箱",
  emailAndCodeRequired: "请填写新邮箱和验证码",
  codeSent: "验证码已发送",
  sendCodeFailed: "发送验证码失败",
  emailUpdated: "邮箱已更新",
  emailChangeFailed: "修改邮箱失败",
} as const;
