from __future__ import annotations

from typing import Protocol

from app.domains.identity.identity_domain import UserRecord


class UserRepository(Protocol):
    def get_by_id(self, user_id: int) -> UserRecord | None: ...

    def get_by_email(self, email: str) -> UserRecord | None: ...

    def get_by_wechat(self, openid: str) -> UserRecord | None: ...

    def email_taken(self, email: str, *, exclude_user_id: int | None = None) -> bool: ...

    def username_exists(self, username: str) -> bool: ...

    def add(self, user: UserRecord) -> UserRecord: ...

    def save(self, user: UserRecord) -> None: ...

    def merge_word_progress(self, user_id: int, device_id: str) -> int: ...

    def reassign_scenarios(self, user_id: int, device_id: str) -> int: ...

    def reassign_attempts(self, user_id: int, device_id: str) -> int: ...

    def reassign_conversations(self, user_id: int, device_id: str) -> int: ...

    def merge_streak(self, user_id: int, device_id: str) -> int: ...
